# Generated by Django 4.2.5 on 2025-04-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Họ và tên học sinh', max_length=100)),
                ('class_name', models.CharField(help_text='Lớp học (ví dụ: Tiger 1, Tiger 2, PIG. CAT, BIRD 1, BIRD 2, BEE)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Ngày của bữa ăn')),
                ('meal_type', models.CharField(choices=[('Bữa sáng', 'Bữa sáng'), ('Bữa trưa', 'Bữa trưa'), ('Bữa xế', 'Bữa xế')], help_text='Chọn loại bữa ăn', max_length=50)),
                ('status', models.CharField(choices=[('Đủ', 'Đủ'), ('Thiếu', 'Thiếu'), ('Bổ sung', 'Bổ sung')], help_text='Trạng thái bữa ăn', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.student')),
            ],
        ),
    ]
