# Generated by Django 4.2.5 on 2025-04-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecord',
            name='status',
            field=models.CharField(choices=[('Đủ', 'Đủ'), ('Thiếu', 'Thiếu')], help_text='Trạng thái bữa ăn', max_length=20),
        ),
    ]
