# Generated by Django 4.2.5 on 2025-04-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_mealrecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên lớp học', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=1, help_text='Lớp học của học sinh', on_delete=django.db.models.deletion.CASCADE, to='meals.classroom'),
            preserve_default=False,
        ),
    ]
