# Generated by Django 4.2.5 on 2025-04-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_classroom_remove_student_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tiền đã đóng', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='last_month_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tiền tháng trước', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='meal_fee_type',
            field=models.CharField(choices=[('type1', '40k/ngày (1,040,000/tháng)'), ('type2', '30k/ngày (780,000/tháng)')], default='type2', help_text='Loại tiền ăn', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tiền còn lại (tiền đã đóng - học phí - (tiền ăn * số ngày ăn))', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Thành tiền (tiền còn lại + tiền tháng trước)', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Học phí', max_digits=10),
        ),
    ]
