# Generated by Django 4.2.5 on 2025-04-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_student_amount_paid_student_last_month_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_month_balance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='meal_fee_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tuition_fee',
        ),
    ]
