# Generated by Django 4.2.5 on 2025-04-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_remove_student_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Ví dụ: 2025-04', max_length=7)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_meal_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_attended', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.student')),
            ],
        ),
    ]
