# Generated by Django 4.2.5 on 2025-04-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_studentpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='days_attended',
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tiền đã đóng'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='daily_meal_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tiền ăn/ngày'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='month',
            field=models.CharField(help_text='Ví dụ: 2025-04', max_length=7, verbose_name='Tháng (YYYY-MM)'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tiền tháng trước'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Còn thiếu/dư'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.student', verbose_name='Học sinh'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Học phí'),
        ),
    ]
