# Generated by Django 4.2.5 on 2025-04-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_remove_studentpayment_days_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='daily_meal_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='month',
            field=models.CharField(help_text='YYYY-MM', max_length=7),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.student'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
