# Generated by Django 4.2.5 on 2025-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_remove_studentpayment_previous_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecord',
            name='non_eat',
            field=models.IntegerField(choices=[(0, 'Ăn đủ'), (1, 'Nghỉ (Có phép)'), (2, 'Nghỉ (Không phép)')], default=0, help_text='Loại trừ bữa ăn: 0 = Ăn đủ, 1 = Nghỉ (Có phép), 2 = Nghỉ (Không phép)'),
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='meal_type',
            field=models.CharField(choices=[('Bữa sáng', 'Bữa sáng'), ('Bữa trưa', 'Bữa trưa')], help_text='Chọn loại bữa ăn', max_length=50),
        ),
    ]
