# Generated by Django 4.2.5 on 2025-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_mealrecord_non_eat_alter_mealrecord_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.IntegerField(choices=[(1, 'Type 1'), (2, 'Type 2')], default=1, help_text='Loại học sinh: 1 hoặc 2'),
        ),
    ]
