# Generated by Django 4.2.5 on 2025-04-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_alter_classroom_options_alter_mealrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'permissions': [('view_statistics', 'Có thể xem thống kê'), ('change_debt', 'Có thể chỉnh sửa công nợ')]},
        ),
    ]
