# Generated by Django 4.2.5 on 2025-04-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_studentpayment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'permissions': [('view_statistics', 'Có thể xem thống kê')]},
        ),
    ]
