# Generated by Django 4.2.5 on 2025-04-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_alter_studentpayment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền đã đóng'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='daily_meal_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Phí ăn hàng ngày'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='month',
            field=models.CharField(help_text='Chọn tháng theo định dạng YYYY‑MM', max_length=7, verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số dư'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.student', verbose_name='Học sinh'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Học phí'),
        ),
    ]
