# Generated by Django 4.2.5 on 2025-04-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_alter_studentpayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'permissions': [('view_statistics', 'Có thể xem thống kê')], 'verbose_name': 'Công nợ học sinh', 'verbose_name_plural': 'Công nợ học sinh'},
        ),
        migrations.AlterUniqueTogether(
            name='studentpayment',
            unique_together={('student', 'month')},
        ),
    ]
