# Generated by Django 4.2.5 on 2025-04-23 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_alter_studentpayment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='Ngày bắt đầu áp dụng mức giá này')),
                ('daily_price', models.PositiveIntegerField(default=30000, help_text='Giá tiền ăn 1 ngày (VND)')),
                ('breakfast_price', models.PositiveIntegerField(default=15000, help_text='Giá tiền bữa sáng (VND)')),
                ('lunch_price', models.PositiveIntegerField(default=15000, help_text='Giá tiền bữa trưa (VND)')),
            ],
            options={
                'verbose_name': 'Cấu hình giá ăn',
                'verbose_name_plural': 'Các cấu hình giá ăn',
                'ordering': ['-effective_date'],
            },
        ),
    ]
