# Generated by Django 4.2.5 on 2025-04-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_mealprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='daily_meal_fee',
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='meal_price',
            field=models.ForeignKey(default=1, help_text='Chọn cấu hình giá ăn áp dụng cho tháng này', on_delete=django.db.models.deletion.PROTECT, to='meals.mealprice', verbose_name='Cấu hình giá ăn'),
            preserve_default=False,
        ),
    ]
