# Generated by Django 4.2.5 on 2025-05-05 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0018_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Audit log', 'verbose_name_plural': 'Các bản ghi audit'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='data',
            field=models.TextField(blank=True, verbose_name='Dữ liệu'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='path',
            field=models.CharField(max_length=200, verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
