# Generated by Django 4.2.5 on 2025-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0019_alter_auditlog_options_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='year',
            field=models.PositiveIntegerField(default=2025, help_text='Năm học của lớp'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'year')},
        ),
    ]
