# Generated by Django 4.2.5 on 2025-06-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0020_classroom_year_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classroom',
            name='term',
            field=models.CharField(default=-1, help_text='Ví dụ: 2025-2026, Hè 2026,…', max_length=20, verbose_name='Học kỳ/Niên khoá'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'term')},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='year',
        ),
    ]
