# Generated by Django 4.2.5 on 2025-06-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0021_alter_classroom_unique_together_classroom_term_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-id'], 'verbose_name': 'Lớp học', 'verbose_name_plural': 'Lớp học'},
        ),
        migrations.AlterModelOptions(
            name='mealrecord',
            options={'ordering': ['-id'], 'verbose_name': 'Bữa ăn', 'verbose_name_plural': 'Bữa ăn'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id'], 'verbose_name': 'Học sinh', 'verbose_name_plural': 'Học sinh'},
        ),
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'ordering': ['-id'], 'permissions': [('view_statistics', 'Có thể xem thống kê')], 'verbose_name': 'Công nợ học sinh', 'verbose_name_plural': 'Công nợ học sinh'},
        ),
    ]
